#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 21 14:23:34 2022

@author: vittoriafantauzzo
"""
import np_manhattan_distance_values
import matplotlib.pyplot as plt
filepath = "Cv-distances.log"
sd_alpha_cal,sd_beta_cal,sd_alpha_ara,sd_beta_ara = np_manhattan_distance_values.np_manhattan_distances([filepath], 8000, 4)
print (sd_alpha_cal)
plt.plot(sd_alpha_cal, sd_beta_cal, '.')
plt.show()
